# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_auto_20170420_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('hard_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('hard_limit', models.IntegerField(null=True)),
                ('allocated', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('expire', models.DateTimeField()),
                ('allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Quotas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Usages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('in_use', models.IntegerField()),
                ('reserved', models.IntegerField()),
                ('until_refresh', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Resources')),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Resources'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Usages'),
        ),
        migrations.AddField(
            model_name='quotas',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Resources'),
        ),
        migrations.AddField(
            model_name='classes',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quota.Resources'),
        ),
    ]
