# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20170420_1457'),
        ('quota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotas',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
        migrations.AddField(
            model_name='usages',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
    ]
