# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0002_auto_20170421_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
