# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20170420_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='project_id',
        ),
        migrations.AddField(
            model_name='quota',
            name='project',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='hard_limit',
            field=models.IntegerField(),
        ),
    ]
