# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_auto_20170420_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quota',
        ),
    ]
