# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0014_auto_20170420_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
