# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0019_auto_20170420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
    ]
