# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0021_auto_20170420_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='target_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
