# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0022_auto_20170420_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='extra',
            field=models.TextField(default='{}'),
        ),
    ]
