# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20170423_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
