# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('extra', models.TextField()),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('domain_id', models.CharField(db_index=True, max_length=64)),
            ],
        ),
    ]
