# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20170420_1457'),
        ('project', '0003_auto_20170420_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain_id',
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
    ]
