# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170420_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra',
            field=models.TextField(default='{}'),
        ),
    ]
