# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20161210_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_site',
            field=models.IntegerField(null=True),
        ),
    ]
