# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_profile_selected_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provider_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_provider',
        ),
    ]
