# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20170401_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar'),
        ),
    ]
