# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20170403_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Sites'),
        ),
    ]
