# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20170423_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_domain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_project',
            field=models.IntegerField(null=True),
        ),
    ]
