# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 20:34
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('url', models.CharField(max_length=512, null=True)),
                ('client_cert', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/kelepirci/palamar-dashboard/palamar/files'), upload_to='ssl')),
                ('client_key', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/kelepirci/palamar-dashboard/palamar/files'), upload_to='ssl')),
                ('ssl_verify', models.BooleanField(default=True)),
                ('ca_cert', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/kelepirci/palamar-dashboard/palamar/files'), upload_to='ssl')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
